export enum TransactionType {
  DEPOSIT = 'DEPOSIT',
  ORDER = 'ORDER',
  ORDER_REWARD = 'ORDER_REWARD',
  FAILED_PAYOUT = 'FAILED_PAYOUT',
  SERVICE_CHARGE = 'SERVICE_CHARGE',
  WITHDRAWAL = 'WITHDRAWAL',
  REFUND = 'REFUND',
}
