export const BaseUrl = {
  AUTH: 'api/v1/auth',
  OTP: 'api/v1/otp',
  USER: 'api/v1/user',
  RIDERS: 'api/v1/riders',
  ADMIN: 'api/v1/admin',
  RIDERS_STATUS: 'api/v1/riders/active-status',
  WALLET: 'api/v1/wallet',
  TRANSACTION: 'api/v1/transaction',
  RATINGS: 'api/v1/ratings',
  LOCATION: 'api/v1/location',
  ORDER: 'api/v1/order',
  STORAGE: 'api/v1/storage-media',
  TASK: 'api/v1/task',
  NOTIFICATION: 'api/v1/notification',
  TICKETS: 'api/v1/tickets',
};
